# Generated by Django 4.2.1 on 2023-05-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=10)),
                ('product_ram', models.IntegerField()),
                ('product_image', models.FileField(default='default-product-image.jpg', upload_to='product-images')),
                ('product_price', models.IntegerField()),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_mst')),
            ],
        ),
    ]
